### ISSUE TITLE
Problems with compiling under windows

### ISSUE THREAD

**Issue by skaug** [cribosch/matchsurv#1]
I have successfully compiled under linux, but not under  windows. One of the compilation
errors is:

dLb1ELb0ELb0ENS_3RowIdEES3_EEvRNS_3MatIT_EERKT3_RKT4_S5_]+0x4b1): undefined reference to `dsyrk_'

I am running Rstudio with R version:

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
version.string R version 3.3.3 (2017-03-06)

Has the package been tested on windows?

Thanks in advance,

Hans

**Comment by cribosch** [comment]
@skaug, the package hasn't been tested on windows. I can't tell you where the error comes from. 
Cristina

**Comment by skaug** [comment]
Thanks. Apparently the problem is that BLAS is not automatically linked under Windows.

I now have the package building without error messages, but when I run
it on an example that runs fine under linux I get the error:

Error in matchpropexc(Surv(time, status) ~ factor(G) + cluster(i), idControl = j,  : 
  cluster vector needed - use cluster in compdata results

when running the line:

m <- matchpropexc(Surv(time,status)~factor(G)+cluster(i), idControl=j, data=d)

Any idea what this can be caused by?

Hans

**Comment by skaug** [comment]
Correction: I get this error message also on linux when I have installed
the current version of the package.

**Comment by cribosch** [comment]
Dear Hans, 

sorry for my late reply. 
This happens because I've updated the script in order to be able to set up the data for different models. Now you have to use first the function compdata and then matchpropexc to estimate the model you want. 
Here is a small example: 

sdd <- compdata(Surv(time, status==1)~1, data=dd, cluster=id, idControl=j)

Note: cluster is now an option. 
I'll recommend you to look at the variable names of the new dataset; some of them are set by default.
And then you can run the model you want:

pairm <- matchpropexc(Surv(exit, status)~1, data=sdd, cluster=cluster, idControl=unexp.subj, weight=weight)

weight is a variable generated by the compdata function, and in data I'm now referring to the new set-up dataset.

Hope this can help you!

Cristina
